### ISSUE TITLE
【发现--资讯--搜索】输入关键字选择文章进入文章详情页后返回搜索页面数据增加

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#167]
## 描述
进入发现--资讯，点击搜索进入搜索页面，输入关键字点击搜索出现与关键字相关的文章，选择文章进入文章详情页，点击”返回“进入搜索页面，已选择进入文章详情页的文章数据增加一条（点击一次文章进入详情页返回搜索页面该文章在搜索列表上增加一次）
## 配图
![image](https://user-images.githubusercontent.com/30249193/32043614-d5494166-ba6d-11e7-875c-48c4f4e89582.png)

**Comment by huhaophp** [comment]
已修复

**Comment by maanrry** [comment]
现在搜索功能不能使用，存在这篇文章的，输入关键字之后点击搜索没有搜索到相关文章

**Comment by maanrry** [comment]
现在搜索功能不能使用，存在这篇文章的，输入关键字之后点击搜索没有搜索到相关文章

**Comment by mutoe** [comment]
问题已过期 新版本资讯搜索可正常使用
