### ISSUE TITLE
【发布--提问】用户邀请自己回答没有提示

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#250]
## 配图
![image](https://user-images.githubusercontent.com/30249193/33200425-816a67a4-d12f-11e7-98d1-c05f46aab67d.png)
登录用户：
![image](https://user-images.githubusercontent.com/30249193/33200450-aa081a76-d12f-11e7-9450-bb3ece297b97.png)

app端：
![image](https://user-images.githubusercontent.com/30249193/33200459-b1899a68-d12f-11e7-8797-82ac5d321192.png)

**Comment by mutoe** [comment]
4.0.0 暂时没有邀请回答功能
