### ISSUE TITLE
【发现--问答--回答详情页】用户添加回答之后还未被采纳不能编辑回答

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#254]
## 描述
用户添加回答（既不是被邀请回答答案也没有被采纳）进入回答详情页点击"更多“按钮没有”编辑“按钮
## 期望
回答项详情页更多按钮情况：
1.只提问者不是回答者：有采纳答案、收藏、举报、取消
2.只回答者：编辑、删除、收藏、举报、取消
3.即是提问者又是回答者：删除、采纳答案、收藏、编辑、举报、取消
4.既不是提问者也不是回答者：收藏、举报、取消

**Comment by mutoe** [comment]
目前还没有底部按钮 先 mark

**Comment by mutoe** [comment]
目前版本没有编辑回答功能
