### ISSUE TITLE
【发现--问答--问题详情页】已邀请悬赏的问题，邀请者还未回答没有用户围观之前显示围观金额

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#265]
## 配图
![image](https://user-images.githubusercontent.com/30249193/33205243-2d553bb4-d141-11e7-8573-a0af7fee5734.png)
## 期望
被邀请者回答问题并有用户围观这个回答之后才会显示围观金额

**Comment by mutoe** [comment]
4.0.0 还没有此功能
