### ISSUE TITLE
【发现--问答--回答详情页】两个用户互为关注时在A用户进入B用户的回答详情页还显示成“已关注”

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#269]
## 配图
目前显示是“互为关注”
![image](https://user-images.githubusercontent.com/30249193/33248226-e5ce4b76-d35e-11e7-8566-2f52a4835b00.png)

**Comment by Jungle68** [comment]
目前缺少顶部用户信息
