### ISSUE TITLE
【发现--问答--话题详情页】专家列表页面标签未显示全

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#280]
## 配图
![image](https://user-images.githubusercontent.com/30249193/33249856-d436da78-d367-11e7-9d2f-c0f56adbe1b3.png)
app端：
![image](https://user-images.githubusercontent.com/30249193/33249869-de67bb52-d367-11e7-8b55-a1fcd57eb78b.png)

**Comment by mutoe** [comment]
4.0.0版本还没有制作该页面
