### ISSUE TITLE
【发布-图片】从相册中一次选择多张图片，发布成功后图片顺序显示混乱

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus-small-screen-client#395]
## 机型
iPhone 7
浏览器：Safari
## 描述
从相册中一次选择多张图片，在发布页面显示的图片顺序相反

## 配图
<img width="272" alt="72d15e81-7f49-4f4c-96c0-3f67cc0bc582" src="https://user-images.githubusercontent.com/25689097/39861073-0aa6c236-5472-11e8-812c-5547f406054c.png">

**Comment by Jungle68** [comment]
H5 不做图片顺序处理
