### ISSUE TITLE
[资讯] 列表页面处理列表图片拼接图片地址错误

### ISSUE THREAD

**Issue by medz** [slimkit/plus-small-screen-client#453]
如图：

![image](https://user-images.githubusercontent.com/5564821/42448246-2e39f076-83af-11e8-91d7-774e3e7a7b5b.png)
![image](https://user-images.githubusercontent.com/5564821/42448256-3a0c24aa-83af-11e8-9665-138aba7094a8.png)

采用了直接拼接 URL 的形式，非常严重的错误！

**Comment by mutoe** [comment]
@medz fixed
