### ISSUE TITLE
利用全局标签自动生成动态首页（向用户自动生成动态信息，包括广告资讯圈子话题

### ISSUE THREAD

**Issue by zuoaihua** [slimkit/plus-small-screen-client#464]
利用全局标签功能，针对用户自动生成不同的动态信息首页

动态推荐页包括广告动态，资讯动态，圈子动态，圈子信息，话题，我关注的人动态，我关注的圈子动态等

生成一个与用户标签相关的聚合动态页

**Comment by Jungle68** [comment]
@zuoaihua  感谢建议 。聚合页面在我们的计划中是有的，只是目前的重心还没在上面
