### ISSUE TITLE
等于（==）和全等于（===）的问题？？

### ISSUE THREAD

**Issue by zhuangguiyang** [slimkit/plus-small-screen-client#465]
![2](https://user-images.githubusercontent.com/30619185/44440783-47381700-a5fc-11e8-9c81-8e63de62a08a.png)

![image](https://user-images.githubusercontent.com/30619185/44440824-75b5f200-a5fc-11e8-9ae8-1a0760e9aaad.png)

因为你们的代码都是用全等于的，导致这三个判断都没有效果,我这边的h5端和后台有好多这样子的问题，将三个等于号改成两个等于号就可以了，有什么办法可以不需要改等于号的嘛？？

**Comment by mutoe** [comment]
@zhuangguiyang  非本项目问题, 请提问前先了解清楚问题所属项目 😖
