### ISSUE TITLE
IM接口报错

### ISSUE THREAD

**Issue by Scodeless** [slimkit/plus-small-screen-client#466]
`错误信息：{error_description: "user not found", error: "invalid_grant"}`

**Comment by mutoe** [comment]
能否提供详细信息, 如当前客户端版本, 是否进行过二次开发, 是否在 `.env` 中填写了 `VUE_APP_EASEMOB_APP_KEY`, 控制台报错截图

**Comment by Scodeless** [comment]
@mutoe `VUE_APP_EASEMOB_APP_KEY`填写了，进首页就报错：`聊天模块又双叒叕报错啦`,``版本号：`,"version": "4.0.0-rc.9"`

**Comment by Scodeless** [comment]
@mutoe  vue使用的还不是很熟练，截个图给大佬看下吧
![_20180822173042](https://user-images.githubusercontent.com/16814170/44455662-2d64f700-a631-11e8-9be7-4b1acf82fda4.jpg)

**Comment by mutoe** [comment]
@Scodeless 用户是在后台添加的还是自行注册的?

**Comment by Scodeless** [comment]
@mutoe 后台添加的

**Comment by Scodeless** [comment]
@mutoe 已经解决了，后台接口环信配置没有配置，谢谢大佬提醒
