### ISSUE TITLE
【发现-圈子详情-详细信息】圈主查看详细信息时，无法修改信息

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus-small-screen-client#474]
## 描述
1. 圈主查看详细信息时，无法修改信息
2. 圈主查看详细信息时，缺少部分设置

账号：残残   密码：123456    圈子：天谴圈

## 配图
<img width="400" alt="2018-08-23 10 35 42" src="https://user-images.githubusercontent.com/25689097/44501555-4e285d80-a6c0-11e8-8d60-0938edb27b38.png">

## 预期
<img width="254" alt="7b6312f7-ebaf-4362-9609-27cb254beb79" src="https://user-images.githubusercontent.com/25689097/44501604-8465dd00-a6c0-11e8-9d7f-93c29ca76542.png">

**Comment by mutoe** [comment]
目前版本不做修改圈子内容等操作
