### ISSUE TITLE
【发现-圈子详情】圈主/管理员/普通成员查看更多操作，缺少部分选项

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus-small-screen-client#482]
## 描述
1. 圈主查看更多操作，缺少 圈子收益、举报管理、黑名单
2. 管理员查看更多操作，缺少 举报管理、黑名单
3. 普通成员查看更多操作，缺少 举报圈子
4. 所有人查看更多操作，缺少“更多操作”title
## 配图
圈主：
<img width="147" alt="2018-08-23 11 12 38" src="https://user-images.githubusercontent.com/25689097/44502726-75cdf480-a6c5-11e8-9f40-727487a5c3a3.png">

管理员：
<img width="213" alt="2018-08-23 11 11 45" src="https://user-images.githubusercontent.com/25689097/44502732-7bc3d580-a6c5-11e8-8690-26082b1f57cc.png">

普通成员：
<img width="148" alt="2018-08-23 11 11 00" src="https://user-images.githubusercontent.com/25689097/44502754-972ee080-a6c5-11e8-9a88-aa91a6fac4d6.png">

## 预期
圈主：
<img width="125" alt="89b5e566-c6fc-4c24-9f0b-a8294a565f14" src="https://user-images.githubusercontent.com/25689097/44502874-0ad0ed80-a6c6-11e8-85d5-f23dc763f2d6.png">

管理员：
<img width="109" alt="dbe5c2f2-c024-42e6-bdc5-feafd51f20d1" src="https://user-images.githubusercontent.com/25689097/44503297-3523aa80-a6c8-11e8-9a1b-d87e9e6a89e5.png">

普通成员：
<img width="105" alt="981ca42e-685c-4355-924d-be9de7091d17" src="https://user-images.githubusercontent.com/25689097/44503299-3654d780-a6c8-11e8-91d0-907a630d6a2a.png">

**Comment by mutoe** [comment]
目前版本没有计划制作圈子收益/举报/黑名单等功能

**Comment by mutoe** [comment]
"更多操作"的 title 也不需要
