### ISSUE TITLE
【发布-发帖】选择圈子与设计图不一致

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#498]
## 配图
![image](https://user-images.githubusercontent.com/30249193/44515215-8184df80-a6f4-11e8-9fee-c87c580dab83.png)

## 设计图
![image](https://user-images.githubusercontent.com/30249193/44515190-72059680-a6f4-11e8-99dc-b3935f28866d.png)

**Comment by Jungle68** [comment]
![image](https://user-images.githubusercontent.com/7939686/44706150-3d6a5400-aad3-11e8-9de1-993a6f9adea2.png)
标题和内容之间缺少分割线
