### ISSUE TITLE
【发现-圈子-圈子详情】圈主无法撤销置顶

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#500]
## 配图
![image](https://user-images.githubusercontent.com/30249193/44516583-0cb3a480-a6f8-11e8-8509-f52a11d13b56.png)
## 用例
![image](https://user-images.githubusercontent.com/30249193/44516835-ae3af600-a6f8-11e8-87a3-5895a75578f2.png)

**Comment by Jungle68** [comment]
![image](https://user-images.githubusercontent.com/7939686/44705723-0e071780-aad2-11e8-918a-75ca11f5ea52.png)
管理员应该是直接置顶帖子和撤销帖子

**Comment by mutoe** [comment]
refer #517
