### ISSUE TITLE
【发现-圈子-圈子详情】圈主和管理员无法对帖子进行操作

### ISSUE THREAD

**Issue by LMTcancan** [slimkit/plus-small-screen-client#506]
## 描述
圈主和管理员无法对帖子进行操作

## 配图
<img width="415" alt="2018-08-23 5 48 23" src="https://user-images.githubusercontent.com/25689097/44518727-97e36900-a6fd-11e8-9c2f-c01afa47be0f.png">

## 预期
<img width="262" alt="cad50370-751e-41d2-991e-9b42784f2f38" src="https://user-images.githubusercontent.com/25689097/44518733-99ad2c80-a6fd-11e8-8b7d-88c374ac42d6.png">

**Comment by mutoe** [comment]
目前版本没有对帖子操作的功能, 延后处理
