### ISSUE TITLE
【圈子-创建圈子】- 几处错误，导致无法创建圈子

### ISSUE THREAD

**Issue by Jungle68** [slimkit/plus-small-screen-client#507]
1. 第一次进入H5，进入圈子主页，创建圈子，选择头像和名字后，选择分类，分类页面没有分类信息，刷新页面又到了创建页面，上次输入的内容已经没有了；

2. 选择标签后反会创建页，标签依然没有显示，表示没有选择成功；

3. 位置，当前定位成功后，显示的是“定位成功”，应该显示具体的城市；
![image](https://user-images.githubusercontent.com/7939686/44695274-011fff00-aaa5-11e8-84dd-646d4a8c605a.png)

**Comment by mutoe** [comment]
## 关于生产环境下无法选择标签的问题

### 问题描述

在生产环境下 (build for production), 创建圈子时, 需要对圈子选择标签, 呼出标签选择页面选择标签后, 返回创建圈子页面, 发现选择的标签并没有显示在标签一栏, 从而无法创建圈子. 

而该问题在开发环境下则不会复现.

该问题同时出现在个人信息页面选择标签的功能.

### 原因分析

经过长达近一周的研究, 最终发现问题的原因出自 webpack 对代码进行压缩时, 将传入回调方法的名字 `nextStep` 压缩成了 `n`(或其它) 来减小文件尺寸, 该问题会导致 Function.name 变成了一个非幂等的属性.

> refer https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#JavaScript_compressors_and_minifiers

 从而导致下面这段代码(**L65**)并没有按照预期来执行
https://github.com/slimkit/plus-small-screen-client/blob/7702f77974e0464dc5e7b4f09e3750fe1549d812/src/page/chooseTags.vue#L61-L66
所以在返回创建圈子页面时, 并没有正确执行回调方法传出已选择的标签.

但是该问题在过去的版本中并没有出现, 所以大胆猜测这可能是 webpack 或 vue-cli 新版本的 bug.

### 修复思路
- 思路1: 在 webpack 配置中, 取消对方法名的压缩
- 思路2: 禁用 Function.name 属性, 避免非幂等操作导致不可预知的问题.
