### ISSUE TITLE
代码建议：修正后台设置动态关闭付费选项后，H5端动态发图片仍显示付费开关

### ISSUE THREAD

**Issue by mickeysu** [slimkit/plus-small-screen-client#527]
问题：目前后台设置动态关闭付费选项后，H5端发图片仍显示付费开关。
经排查PostImage.vue不正常，但PostText.vue是正常的。代码文件/src/page/post/PostImage.vue文件的修改建议如下：
1、v-switch标签增加属性v-if="paycontrol"如下：：
      &lt;v-switch
        v-if="paycontrol"
        v-model="pinned"
        class="m-box m-bt1 m-bb1 m-lim-width m-pinned-row"
        type="checkbox">
        &lt;slot&gt;是否收费&lt;/slot&gt;
      &lt;/v-switch&gt;
2、computed下增加读取状态的代码：
  computed: {
    ...mapGetters(["compose", "composePhoto"]),
    //******** 读取状态 *************
    paycontrol() {
      return this.$store.state.CONFIG.feed.paycontrol;
    },
    //*********************************

**Comment by mutoe** [comment]
@mickeysu 感谢反馈，将在下个版本修复
