### ISSUE TITLE
【全局支付】触发支付的需要输入登录密码，但没有弹出输入框

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#540]
## 描述
触发支付的需要输入登录密码，但没有弹出输入框

**Comment by mutoe** [comment]
## 以下内容涉及积分需要支付密码验证
### 全局打赏
- [ ] 动态打赏
- [ ] 资讯打赏
- [ ] 用户打赏
- [ ] 回答打赏
- [ ] 帖子打赏

### 全局申请置顶
- [ ] 动态置顶
- [ ] 动态评论置顶
- [ ] 资讯置顶
- [ ] 资讯评论置顶
- [ ] 帖子置顶
- [ ] 帖子评论置顶

### 其他
- ~~发布悬赏问题~~
- ~~设置问题悬赏~~
- ~~问题申请精选~~
- ~~答案围观~~
- [ ] 加入付费圈子
- [ ] 资讯投稿付费

> 注：h5目前无问题悬赏、围观答案、申请问题精选等功能
