### ISSUE TITLE
【全局长图】长图比例计算不对

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#541]
## 描述
长图比例：长：宽！=3:1 ，现在仍然算是长图
动态：http://test-plus.zhibocloud.cn/h5/feeds/934
## 期望
![image](https://user-images.githubusercontent.com/30249193/46599579-490d5980-cb1a-11e8-81fa-e98ead30f74b.png)

**Comment by mutoe** [comment]
已修复
