### ISSUE TITLE
【发布图片动态】后台关闭发布动态付费开关之后，发布图片页面仍然有付费开关

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#543]
## 配图
![image](https://user-images.githubusercontent.com/30249193/46858559-1e830f80-ce3e-11e8-846c-45f223db5ff8.png)

后台：
![image](https://user-images.githubusercontent.com/30249193/46600456-cb971880-cb1c-11e8-9797-549b1c2c8a79.png)

**Comment by mutoe** [comment]
fixed via #527

**Comment by maanrry** [comment]
1012复测：未修复
