### ISSUE TITLE
【我的-设置-关于我们】查看关于我们的内容详情页面左上角缺少返回按钮

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#549]
## 配图
![image](https://user-images.githubusercontent.com/30249193/46708739-c64be200-cc72-11e8-88ff-ad937e8c294c.png)
## 期望
同Android端一样
![image](https://user-images.githubusercontent.com/30249193/46708772-ef6c7280-cc72-11e8-8d8a-28e31f098285.png)

**Comment by mutoe** [comment]
**无法修复**
原因：无法做到在外链页面上含有我们自己的header栏，android端使用的是webview渲染网页，其顶部是app内部的顶部，spa使用的是iframe嵌入外链网页，如果外链网页设置了禁止iframe嵌入的头`X-Frame-Options`(该头用来确保自己网站的内容没有被嵌到别人的网站中去)，则不能正常加载外链网页

![image](https://user-images.githubusercontent.com/9391981/46938331-11605d80-d096-11e8-90c7-7ec19ce17ad2.png)

**Comment by Jungle68** [comment]
不予处理
