### ISSUE TITLE
【发现-问答】整个问题列表的时间都是错误的

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#559]
## 配图
![image](https://user-images.githubusercontent.com/30249193/46716007-e5f40200-cc94-11e8-8a46-39e07e6da446.png)
Android端：
![image](https://user-images.githubusercontent.com/30249193/46716070-1b005480-cc95-11e8-9044-900397275aa2.png)
## 期望
![image](https://user-images.githubusercontent.com/30249193/46716086-2a7f9d80-cc95-11e8-94ad-0d642a586f42.png)

**Comment by maanrry** [comment]
12号复测未修复

**Comment by mutoe** [comment]
现在逻辑
1. 当时间小于1分钟时，显示`1分钟内`
2. 当小于1小时， 显示`x分钟前`
3. 当小于24小时，显示`x小时前`
4. 当小于48小时，显示`昨天 14:23`
5. 当小于9*24小时，显示`x天前`
6. 否则显示 `05-12`
@maanrry 请确认

**Comment by Jungle68** [comment]
最新的时间排序任然是错误的， 可参考安卓

**Comment by mutoe** [comment]
是问答列表的时间显示字段的问题，已修改为创建时间
