### ISSUE TITLE
【发现-问答-问题详情】已邀请悬赏的问题在问题详情显示不对

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#572]
## 配图
问题链接：http://test-plus.zhibocloud.cn/h5/questions/94
![image](https://user-images.githubusercontent.com/30249193/46720187-640ad580-cca2-11e8-9256-4e3f3fd6a6c4.png)
## 期望
已邀请悬赏显示----已邀请悬赏并且点击之后小弹窗显示被邀请者的昵称和头像（参考Android端）
仅设置悬赏的问题显示----已设置悬赏
未设置悬赏的问题显示---未设置悬赏

**Comment by mutoe** [comment]
点击小弹框显示被邀请者昵称和头像为新功能
