### ISSUE TITLE
【找人-推荐】没有取与用户标签相关的用户

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-small-screen-client#576]
## 描述
推荐分类现在仅取了后台推荐的用户
## 用例
![image](https://user-images.githubusercontent.com/30249193/46725649-3415ff00-ccaf-11e8-8cde-aa927ff21193.png)

**Comment by mutoe** [comment]
混合数据，拼接数据无法做到按需调用不同接口

目前做法，加载全部推荐用户和第一屏标签匹配用户，然后如果有剩余，则可以下拉加载更多
