### ISSUE TITLE
授权版圈子发帖之后返回帖子列表，帖子列表不更新的修正建议

### ISSUE THREAD

**Issue by mickeysu** [slimkit/plus-small-screen-client#587]
圈子里面发帖，发帖发表返回帖子列表，列表内容不更新，修正建议：
在GroupDetail.vue文件第319至313行的位置加入groupPostDetail路由判断调用getFeeds进行刷新，修复后代码如下：
  watch: {
    $route(to, from) {
      if (from.name === "groupPostDetail") this.getFeeds();   //修改建议位置：刷新列表
      if (from.name === "groupDetail") return;
      this.showSlide = from.meta.sidebar;
    },

**Comment by mutoe** [comment]
@mickeysu 该问题已在v4.0.2版本中修正，请更新到v4.0.2版本即可解决该问题
> https://github.com/slimkit/plus-small-screen-client/commit/50731f777e1282e2f7201dde7cbbd32bc87f9480#diff-7da266ec6551deeaf8dba48654070b25
