### ISSUE TITLE
在qq分享内置浏览器内，点击右上角本身系统的浏览器分享后，分享出去的动态内容，内容缩略和icon没有显示出来

### ISSUE THREAD

**Issue by hantianlong** [slimkit/plus-small-screen-client#87]
![2](https://user-images.githubusercontent.com/28078379/27779867-35482260-5ff8-11e7-9351-2e86a0292eff.jpg)

**Comment by mutoe** [comment]
v4 无此问题
分享动态只有含有图片的动态才可显示缩略图
